### ISSUE TITLE
运行时MongoDB发生StrictModeError

### ISSUE THREAD

**Issue by joecwu** [xuduo/socket.io-push#27]
请问这问题该如何解决?
```
8/7/2017, 9:11:20 PM worker:03 I/Mongo query  socket-io-push_devices findAndModify { _id: 'v82ytThWiweosl60' }
8/7/2017, 9:11:20 PM worker:03 D/DeviceService connect  { id: 'v82ytThWiweosl60',
  version: 1,
  platform: 'browser',
  topics: [ 'noti', 'chatRoom' ],
  lastUnicastId: null,
  lastPacketIds: {} } { _id: 'v82ytThWiweosl60',
  __v: 0,
  updateTime: 2017-08-07T13:11:20.967Z,
  socketId: '192.168.70.31:6QdyZ84e-AzMsBmsAAAE',
  createTime: 2017-08-07T13:11:11.121Z,
  tags: [] } null
8/7/2017, 9:11:21 PM worker:01 I/Mongo query  socket-io-push_sessions update { _id: '192.168.70.31:1' }
8/7/2017, 9:11:21 PM worker:02 I/Mongo query  socket-io-push_sessions update { _id: '192.168.70.31:2' }
8/7/2017, 9:11:21 PM worker:01 E/TopicOnline topicOnline.update  { MongooseError: Path "_id" is not in schema, strict mode is `true`, and upsert is `true`.
    at StrictModeError (/Users/joecwu/node_modules/mongoose/lib/error/strict.js:21:11)
    at cast (/Users/joecwu/node_modules/mongoose/lib/cast.js:199:17)
    at model.Query.Query.cast (/Users/joecwu/node_modules/mongoose/lib/query.js:3103:12)
    at model.Query.Query._castConditions (/Users/joecwu/node_modules/mongoose/lib/query.js:1144:10)
    at model.Query.Query._execUpdate (/Users/joecwu/node_modules/mongoose/lib/query.js:2321:8)
    at /Users/joecwu/node_modules/kareem/index.js:250:8
    at /Users/joecwu/node_modules/kareem/index.js:23:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  message: 'Path "_id" is not in schema, strict mode is `true`, and upsert is `true`.',
  name: 'StrictModeError',
  path: '_id' }
```

**Comment by xuduo** [comment]
安装@0.8.96

**Comment by joecwu** [comment]
谢谢!
