### ISSUE TITLE
addArrivalInfo对APN推送支持标题和消息体的问题

### ISSUE THREAD

**Issue by kk17** [xuduo/socket.io-push#33]
现在苹果APN推送支持标题和消息体区分，但是socket.io-push的支持有问题，
如果推送notification为下面数据的话，
```
{
    "android": {
        "message": "消息体",
        "title": "消息标题",
        "payload": {...}
    },
    "apn": {
        "alert": {
            "body": "消息体",
            "title": "消息标题"
        }
    },
    "id": "rOW60mpqNLxY",
    "timestamp": 1511411873267
}
```

ArrivalStats的addArrivalInfo会出现异常
```
2017-11-23 12:37:53 worker:07 D/ArrivalStats addArrivalInfo  rOW60mpqNLxY { '$inc': { target_android: 1 },
  '$set':
   { notification: { body: '消息体', title: '消息标题' },
     timeStart: 1511411873285,
     ttl: 0,
     expireAt: 1514003873285,
     type: 'pushMany' },
  '$setOnInsert': { __v: 0 } } { ok: 0, n: 0, nModified: 0 } { MongooseError: Cast to string failed for value "{ body: '消息体', title: '消息标题' }" at path "notification"
    at CastError (/home/webedit/socket.io-push/push-server/node_modules/mongoose/lib/error/cast.js:26:11)
    at SchemaString.cast (/home/webedit/socket.io-push/push-server/node_modules/mongoose/lib/schema/string.js:458:9)
    at SchemaString.SchemaType._castForQuery (/home/webedit/socket.io-push/push-server/node_modules/mongoose/lib/schematype.js:1064:15)
    at SchemaString.SchemaType.castForQueryWrapper (/home/webedit/socket.io-push/push-server/node_modules/mongoose/lib/schematype.js:1019:17)
    at castUpdateVal (/home/webedit/socket.io-push/push-server/node_modules/mongoose/lib/services/query/castUpdate.js:308:19)
    at walkUpdatePath (/home/webedit/socket.io-push/push-server/node_modules/mongoose/lib/services/query/castUpdate.js:150:20)
    at castUpdate (/home/webedit/socket.io-push/push-server/node_modules/mongoose/lib/services/query/castUpdate.js:71:18)
    at model.Query._castUpdate (/home/webedit/socket.io-push/push-server/node_modules/mongoose/lib/query.js:2902:10)
    at _update (/home/webedit/socket.io-push/push-server/node_modules/mongoose/lib/query.js:2752:23)
    at model.Query.Query.update (/home/webedit/socket.io-push/push-server/node_modules/mongoose/lib/query.js:2547:10)
    at _update (/home/webedit/socket.io-push/push-server/node_modules/mongoose/lib/model.js:2453:16)
    at Function.update (/home/webedit/socket.io-push/push-server/node_modules/mongoose/lib/model.js:2369:10)
    at ArrivalStats.addArrivalInfo (/home/webedit/socket.io-push/push-server/lib/stats/arrivalStats.js:37:26)
    at ArrivalStats.addPushMany (/home/webedit/socket.io-push/push-server/lib/stats/arrivalStats.js:81:10)
    at NotificationService.sendByDevices (/home/webedit/socket.io-push/push-server/lib/service/notificationService.js:35:22)
    at ApiRouter.sendNotificationByDevices (/home/webedit/socket.io-push/push-server/lib/service/apiRouter.js:162:30)
  message: 'Cast to string failed for value "{ body: \'消息体\', title: \'消息标题\' }" at path "notification"',
  name: 'CastError',
  stringValue: '"{ body: \'消息体\', title: \'消息标题\' }"',
  kind: 'string',
  value: { body: '消息体', title: '消息标题' },
  path: 'notification',
  reason: undefined }
```

**Comment by xuduo** [comment]
payload  应该在最外层， 参照下api文档的例子

**Comment by kk17** [comment]
现在说的不是playload的问题

**Comment by xuduo** [comment]
https://github.com/xuduo/socket.io-push/commit/89c5ef031e21070b71711fe16131376e2df8528c

之前开发的时候似乎不支持，我改了下， 0.9.8版本
